// Generated by CoffeeScript 1.6.2
/*
Jikamu Router - Requires a Page object and this will be serve as the page for 
the Apps, and it will add the URL rules that will be needed by the Router Class 
later on.

Thanks to DavisJS and I got an idea how to match or create pattern for Jikamu.AppListener
*/

var nameRegex, pathNameRegex, pathNameReplacement, splatNameRegex, splatNameReplacement;

Jikamu.routes = [];

/*
Regex pattern from DavisJS.coms
*/


pathNameRegex = /:([\w\d]+)/g;

pathNameReplacement = "([^/]+)";

splatNameRegex = /\*([\w\d]+)/g;

splatNameReplacement = "(.*)";

nameRegex = /[:|\*]([\w\d]+)/g;

Jikamu.Route = (function() {
  function Route(route_config) {
    this.properties = {
      urlpath: false,
      page: function() {}
    };
  }

  Route.prototype.urlpath = function(new_urlpath) {
    if (new_urlpath) {
      this.properties.urlpath = this.convertUrlPathtoRegExp(new_urlpath);
      return this;
    } else {
      throw "Jikamu.Route: Empty or Invalid url path";
    }
  };

  Route.prototype.page = function(obj) {
    this.properties.page = new Jikamu.Page().page_name(obj.page_name).controller(obj.controller).before_load(obj.before_load).after_load(obj.after_load);
    return this;
  };

  Route.prototype.convertUrlPathtoRegExp = function(path) {
    var str;

    if (!(path instanceof RegExp)) {
      str = path.replace(pathNameRegex, pathNameReplacement).replace(splatNameRegex, splatNameReplacement);
      path.lastIndex = 0;
      if (window.Jikamu.DEBUG) {
        console.log("Converts " + path + " and it converts to " + (new RegExp("^" + str + "$", "gi")));
      }
      return new RegExp("^" + str + "$", "gi");
    } else {
      if (window.Jikamu.DEBUG) {
        console.log("Pass the original path variable");
      }
      return path;
    }
  };

  /*
  Save Route - saves the current route object to the global variable Jikamu.routes
  
  @method: save
  */


  Route.prototype.save = function() {
    var _arr;

    _arr = {};
    _arr.urlpath = this.properties.urlpath;
    _arr.handler = this.properties.page;
    Jikamu.routes.push(_arr);
    return this;
  };

  return Route;

})();
