// Generated by CoffeeScript 1.6.2
/*
Jikamu.Page - provide the page template for Jikamu App
*/
Jikamu.Page = (function() {
  function Page() {
    this.properties = {
      page_name: false,
      controller: function() {},
      before_load: function() {},
      after_load: function() {}
    };
  }

  Page.prototype.page_name = function(new_page_name) {
    if (new_page_name) {
      this.properties.page_name = new_page_name;
      return this;
    } else {
      throw "Jikamu.Page: Invalid page_name";
    }
  };

  Page.prototype.controller = function(new_controller) {
    if (typeof new_controller === "function") {
      this.properties.controller = new_controller;
      return this;
    } else {
      throw "Jikamu.Page: Invalid controller this should be a function";
    }
  };

  /*
  @deprecated
  */


  Page.prototype.before_load = function(new_before_load) {
    if (typeof new_before_load === "function") {
      this.properties.before_load = new_before_load;
      return this;
    } else {
      throw "Jikamu.Page: Invalid before load callback this should be a function";
    }
  };

  /*
  @deprecated
  */


  Page.prototype.after_load = function(new_after_load) {
    if (typeof new_after_load === "function") {
      this.properties.after_load = new_after_load;
      return this;
    } else {
      throw "Jikamu.Page: Invalid after load callback this should be a function";
    }
  };

  return Page;

})();
